spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5332/mmlog-db
spring.datasource.username=mmlog_user
spring.datasource.password=H@Nk+ank25
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true 