services:
  postgres:
    image: 'postgres:latest'
    container_name: 'spring-boot-pg'
    environment:
      - 'POSTGRES_DB=mmlog-db'
      - 'POSTGRES_PASSWORD=H@Nk+ank25'
      - 'POSTGRES_USER=mmlog_user'
    ports:
      - '5332:5432'
